---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true
  customize:
    memory: 512

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box

suites:
- name: default
  run_list:
    - recipe[gvm]
  attributes:
    gvm:
      default_version: go1.1.2
      versions:
        - go1.1.2

- name: user
  run_list:
    - recipe[gvm::user]
  attributes:
    gvm:
      user_default_version: go1.1.2
      user_versions:
        - go1.1.2
      user_installs:
        - vagrant
